### ISSUE TITLE
Uploading large images as profile pictures crashes app and removes last uploaded profile picture.

### ISSUE THREAD

**Issue by colelewis** [SCCapstone/Mind404#69]
When uploading arbitrarily large images as profile pictures, the app crashes and removes the last profile picture uploaded, leaving behind the default avatar image. 

I conducted this test twice, but was hesitant to try other sizes as I didn't want to use up all your Firestore data by repeatedly uploading images, so I couldn't say exactly what the tolerable limit of file size is. As seen in the attached screen recording, the image I used to test is approximately 375 MB in size. While this would be ridiculous for someone to actually try and do, I would still recommend some sort of validation (~10MB?) on the size of the an image before uploading.

Additionally, upon crashing, user is not automatically logged back in, and username/password fields are left blank.

https://user-images.githubusercontent.com/18597672/163070843-07281d06-4a86-4c99-8376-372057722180.mov

**Comment by KTPrince** [comment]
@rseas We're done testing!  Thought this was easier than opening a whole new issue about it.
